### ISSUE TITLE
Explain how to connect to Titan

### ISSUE THREAD

**Issue by jvilledieu** [Linkurious/linkurious-enterprise-manual#10]

**Comment by jvilledieu** [comment]
"graphdb": {
    "vendor": "neo4j",
    "url": "http://127.0.0.1:7474",
    "user": null,
    "password": null,
    "webAdmin": "http://127.0.0.1:7474/browser"
   },
   "index": {
    "vendor": "elasticSearch",
    "host": "127.0.0.1",
    "port": 9201,
    "forceReindex": false,
    "dynamicMapping": true,
    "indexName": "linkurious_f5ccec0e"
   }
  },
  {
   "graphdb": {
    "vendor": "titan",
    "url": "ws://192.168.0.35:8182",
    "configurationPath": "/Users/david/Code/linkurious-server/test/data/titan-cassandra-es.properties"
   },
   "index": {
    "vendor": "elasticSearch",
    "host": "127.0.0.1",
    "port": 9201,
    "forceReindex": false,
    "dynamicMapping": false
   }
  }

**Comment by davidrapin** [comment]
To configure a Titan graph database, use the the following fields in the "graphdb" section of the source configuration:
 - "url" must be in the form "ws://[GREMLIN_SERVER_IP]:[GREMLIN_SERVER_PORT]" (e.g. "ws://192.168.0.5:8182")
 - "configurationPath" must be the absolute path of the Titan configuration file on the Gremlin server (e.g. "/usr/local/titan/conf/titan-cassandra-es.properties")

**Comment by sheymann** [comment]
done in:
- [x] English
- [ ] French
- [ ]  Spanish

**Comment by eduramiba** [comment]
Hi,
I can translate this small part when I have some spare time..

**Comment by sheymann** [comment]
thanks Eduardo! it's on Getting Started > Configure, se commit https://github.com/Linkurious/linkurious-enterprise-manual/commit/251c79e1ab2f9f739ed3be680ac9ab7f8e5fa207
