### ISSUE TITLE
Explain how to configure LK to use ES Shield authentication

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious-enterprise-manual#11]

**Comment by sheymann** [comment]
@davidrapin need config sample and explanation

**Comment by davidrapin** [comment]
Allow ElasticSearch config options:
```ES6
{
  "host": "192.68.0.45", // the ES host
  "port" 9200, // the ES port
  "forceReindex": false, // whether to force re-index on restart
  "dynamicMapping": false, // whether to detect number automatically (fragile)
  "dateDetection": false, // whether to detect dates automatically (fragile)
  "user": "john", // ElasticShield username 
  "password": "pass123" // ElasticShield password
  "https": true // whether to connect to ES via HTTPS (recommended for ElasticShield)
}
```

**Comment by davidrapin** [comment]
non documented alter native if you are crazy-sure of what you're doing:
{
  "vendor": "elasticSearch",
  "url": "http://john!pass123@192.168.0.45:9200/", // Yep, you can do that too (if "url" is set, "host", "port", "user", "password" and "https" are ignored)
  "forceReindex": false, // whether to force re-index on restart
  "dynamicMapping": false, // whether to detect number automatically (fragile)
  "dateDetection": false, // whether to detect dates automatically (fragile)
}

**Comment by sheymann** [comment]
- [x] english
- [ ] french
- [ ] spanish
