### ISSUE TITLE
Add "How to migration from SQLite to MySQL"

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious-enterprise-manual#13]

**Comment by davidrapin** [comment]
⚠️ actually try this out. 

Export the SQLite database to a file:
`sqlite3 ./linkurious-linux/data/server/database.sqlite .dump > export.sql`

Load the exported database back into MySQL
`mysql -u myMysqlUser -p -h localhost linkurious < export.sql`

**Comment by sheymann** [comment]
done
