### ISSUE TITLE
How to deploy on AWS/Azure

### ISSUE THREAD

**Issue by sheymann** [Linkurious/linkurious-enterprise-manual#16]
Need step-by-step tutorial on how to deploy on major cloud platforms.

refs https://secure.helpscout.net/conversation/245263566/371/?folderId=490086

**Comment by davidrapin** [comment]
Nothing unusual to do.

1. create an AWS-ES instance (https://aws.amazon.com/fr/elasticsearch-service/)
2. set the index.host and index.port in the `dataSource` configuration
3. ???
4. profit

**Comment by sheymann** [comment]
Hmm I need screenshots and really dummy step-by-step here, not the overview. Imagine helping someone who never used AWS or Azure and they are asked for using them.

**Comment by davidrapin** [comment]
this?
http://doc.linkurio.us/content/en/others/elasticsearch_on_aws.html

**Comment by sheymann** [comment]
No this doc is how to use ES on AWS. I mean a dummy guide from "here is my AWS dashboard" to "LK is up and running".

**Comment by davidrapin** [comment]
Please open an issue on the documentation repo, this repo is retired.

David Rapin
CTO & Cofounder
http://linkurio.us
