### ISSUE TITLE
Help for continuous indexation

### ISSUE THREAD

**Issue by jvilledieu** [Linkurious/linkurious-enterprise-manual#18]
Right now the topic of continuous indexation is mentioned in the "configure" section which refers to "read Continuous indexation in Neo4j" without providing a link.

**Comment by sheymann** [comment]
@davidrapin can you provide a link or improve the documentation regarding continuous indexation please?

**Comment by davidrapin** [comment]
I don't have the time to do this right. I'll work on it next week.

**Comment by davidrapin** [comment]
https://github.com/Linkurious/linkurious-enterprise-manual/blob/master/en/others/neo4j_to_elasticsearch_synchronization.md

**Comment by sheymann** [comment]
done at https://doc.linkurio.us/admin-manual/1.6.0/search-neo4j/
