### ISSUE TITLE
Add pattern queries

### ISSUE THREAD

**Issue by jvilledieu** [Linkurious/linkurious-enterprise-manual#8]
Currently not mentioned.
Perhaps in the Search chapter?

**Comment by JChheub** [comment]
Oui ça me semble cohérent, après "Advanced syntax".
Is there a link where the queries are listed?

**Comment by sheymann** [comment]
@jvilledieu we need examples of a few queries for Crunchbase to move forward

**Comment by davidrapin** [comment]
a good introduction:
http://neo4j.com/docs/developer-manual/current/#cypher-query-lang

David Rapin
CTO & co-founder
http://linkurio.us

On Thu, May 19, 2016 at 3:16 PM, Sébastien Heymann <notifications@github.com

**Comment by jvilledieu** [comment]
Some possible queries: https://linkurio.us/crunchbase-graph-analysing-graph/

**Comment by davidrapin** [comment]
@jvilledieu actually the queries have to return nodes and edges so most of the queries from your link wouldn't work.

**Comment by sheymann** [comment]
Also need to add Gremlin queries

**Comment by sheymann** [comment]
@jvilledieu need query examples

**Comment by jvilledieu** [comment]
//What is the biggest startup scene?
MATCH (a:CITY)<-[r:HAS_CITY]-(b:COMPANY)
WITH count(b) as score, a, b, r
RETURN a, b, r
ORDER BY score DESC
LIMIT 25

**Comment by jvilledieu** [comment]
?

**Comment by davidrapin** [comment]
http://doc.linkurio.us/content/en/search/pattern_search.html
